version: "3"
services:
  app:
    image: avisdockerstore/devops-for-programmers-project-lvl1:latest
    build:
      context: /app
      dockerfile: Dockerfile.production
    command: make test
    volumes:
      - "./app:/app"
    

