version: "3"
services:

  app:
    env_file:
      - ./app/.env
    image: avisdockerstore/devops-for-programmers-project-lvl1:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
#    depends_on:
#     - db
#
#  db:
#    env_file:
#      - ./app/.env
#    image: postgres:latest
#

    

