version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    volumes:
      - "./app:/app"
    image: avisdockerstore/devops-for-programmers-project-lvl1:latest

