name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   

      - name: Run tests
        run: ../../make ci

      - name: Build & push the image
        run: |
          ../../docker-compose -f docker-compose.yml build app
          ../../docker-compose -f docker-compose.yml push app
