name: push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:   
      - name: copy env file
        run:          
          cp .env.example app/.env

      - uses: actions/checkout@v2
      - name: Run tests      
        run:          
          make ci


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push the image
        run: |
          docker-compose -f docker-compose.yml build app
          docker-compose -f docker-compose.yml push app
        
