name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: make test

      # Runs a set of commands using the runners shell
      - name: Build & push the image
        run: |
          docker-compose -f docker-compose.yml build app
          docker-compose -f docker-compose.yml push app
